### PR TITLE
[wip] fix: specify repo explicitly for update-electron-app

### PR DESCRIPTION
**Pull request by zeke**
Bypasses this by setting repo explicitly:

image

cc @codebytere

### CODE REVIEW

**Comment by zeke** [comment]
This is what's failing: https://github.com/electron/update-electron-app/blob/be2d4c1f451243624e92b855c8aaf6ff12d50552/index.js#L107 -- not sure why, and I haven't seen this before from other apps using update-electron-app.

**Comment by zeke** [comment]
Wait!

I think this is because when you `npx` you’re basically running the app in dev mode. It's not a packaged app. So we need to wrap the `update-electron-app` invocation in some kind of check.

**Comment by zeke** [comment]
The `update-electron-app` module is designed to abort early if the app is in "development". See https://github.com/electron/update-electron-app/blob/be2d4c1f451243624e92b855c8aaf6ff12d50552/index.js#L24-L29

For some reason this `npx` thing is getting past that check.

**Comment by ckerr** [comment]
Marking as `[wip]` to avoid premature merging. Based on Zeke's remarks above https://github.com/electron/electron-api-demos/pull/392#issuecomment-415533142 it looks like there's some research to be done?

**Pull request closed without merging**
