### PR TITLE
Keep electron and spectron minor version numbers in sync

### PR DESCRIPTION
**Pull request by zeke**
Working toward #294 

I just did a fresh `rm -rf node_modules && npm i && npm t`. The app window appears on screen, but the test suite is hanging on setup and it times out before any of the tests are run.

The [docs for `app.start()`](https://github.com/electron/spectron/#start) say that it returns a promise when the app is ready, but it seems the `setupApp` function is never reached.

Any ideas, @kevinsawicki?

### CODE REVIEW

**Comment by kevinsawicki** [comment]
@zeke hmm, not sure, the tests appear to pass on Travis, are the changes here your only local changes?

**Comment by zeke** [comment]
No local changes. Just pulling from master and starting from scratch.

**Comment by zeke** [comment]
Locking `electron` at  1.4.15 seems to fix it.

**Comment by zeke** [comment]
I had forgotten that Electron and Spectron have to have corresponding minor version numbers. This PR bumps them both to the latest and uses a `~` prefix to allow patch levels to fluctuate.

Here's a PR on Spectron to help make that more obvious to users: https://github.com/electron/spectron/pull/166

**Pull request merged**
