### PR TITLE
Fix handling of the custom protocol on windows

### LINKED ISSUE #271: Custom protocols not showing the error box on windows
* What operating system are you using? 
Windows 10

* What version of Node.js is on your system?
None

I tried to use your demo of custom protocols because it's supposed to be supported on OSX and Windows :

screen shot 2016-10-13 at 16 32 33

I made some tests and it works perfectly on OSX, the error box is popping, telling me what URI I clicked on.
But on Windows, the error box doesn't appear, only the application is popping. 

As far as I understand : 
 - the error box is displayed because `app.on('open-url')` is only available on macOS
 - the application is displayed on Windows thanks to `

My point is it possible to implement a way to show the error box on Windows ?

You might want to check PR #270 as well.

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #271

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
This allows the defaultProtocolClient to work from `npm start` (so you don't need to be packaged for it to work).  It also makes the alert appear on windows by handling the `argv` parameter in the `makeSingleInstance` callback

**Comment by zeke** [comment]
@MarshallOfSound if https://github.com/electron/electron/pull/8052 lands, would it render this PR unnecessary?

**Comment by MarshallOfSound** [comment]
Yep

**Comment by MarshallOfSound** [comment]
@zeke Actually a subsection of this PR is still required to make the protocol handler work from a non-packaged version of the app

**Comment by zeke** [comment]
Just checking in here. @MarshallOfSound is this still something you want to ship eventually?

**Comment by MarshallOfSound** [comment]
Yeah, the PR in Electron needs to ship first though

**Comment by ckerr** [comment]
@MarshallOfSound are this and https://github.com/electron/electron/pull/8052 still something that you want to land? If so, is there anything I can do to help unblock these two?

**Comment by ckerr** [comment]
@MarshallOfSound ping :D

**Comment by codebytere** [comment]
oh wait i lied, the other one landed so this is unnecessary

**Comment by codebytere** [comment]
Closing in favor of updated one.

**Pull request closed without merging**
