### PR TITLE
Win focus demo

### PR DESCRIPTION
**Pull request by andypavia**
Added a win.focus() API demo 😺

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for the PR, @andypavia. I will defer to @jlord to make the call about whether to land this in the app or not.

I notice the CI is failing. Are you able to fix those issues?

**Comment by jlord** [comment]
@andypavia thanks for contributing! I'm a little iffy on adding this to the manage state demo. It introduces a new UI element to the app that will just be here and was a bit confusing to me as it shows up even when the demo window is in focus:

screen shot 2016-08-22 at 2 26 29 pm

I also wonder if it adds too much complexity to this demo and might perhaps be better off as a new demo entirely (as in a fourth in this section)?

**Comment by andypavia** [comment]
@jlord yeah you're right. It is easy a little bit confusing. Maybe use win.isFocused() and BrowserWindow blur event to not show the button when the demo window is in focus? I can also create a new section for the demo 😄.

@zeke It's the white space. I'll make sure to clean it up on the next PR.

**Comment by Haacked** [comment]
> I'll make sure to clean it up on the next PR.

No need to create a new PR. Just make the changes and push to this branch and the PR will update. Unless I misunderstood what you mean.

Are you still planning to work on this? The more demos the better!

**Comment by andypavia** [comment]
@Haacked Yup I still plan to make this happen. Sorry for the delay.

**Comment by Haacked** [comment]
> @Haacked Yup I still plan to make this happen. Sorry for the delay.

No apologies necessary. I was just taking a pass through stale PRs and issues. We understand you all have day jobs and other responsibilities. :smile:

**Comment by andypavia** [comment]
@Haacked @jlord let me know what you think :)

**Comment by zeke** [comment]
@andypavia the CI failed. There's a check in there for the number of demos. You'll need to change `27` to `28`. :)

**Comment by zeke** [comment]
One step closer! Now there are some linting errors:

```
> ElectronAPIDemos@1.1.0 lint /home/travis/build/electron/electron-api-demos
> standard | snazzy
standard: Use JavaScript Standard Style (http://standardjs.com) 
/home/travis/build/electron/electron-api-demos/renderer-process/windows/manage-window.js
  20:2  error  Newline required at end of file but not found
/home/travis/build/electron/electron-api-demos/renderer-process/windows/using-window-events.js
  20:5  error  Expected space                                 s
  29:2  error  Newline required at end of file but not found
✖ 3 problems
```

**Comment by Haacked** [comment]
Nice work @andypavia. I just tried it out and I think this ended up in a good place. :sparkles:

**Comment by andypavia** [comment]
Awesome! 😄 @Haacked @zeke thanks for the help!

**Comment by zeke** [comment]
@andypavia I'll let you know when the next release lands.

**Pull request merged**
