### PR TITLE
Add snazzy to linting

### PR DESCRIPTION
**Pull request by crookedneighbor**
Love the demo. Was playing around with it and it took me an extra minute or two to figure out what linting errors I was tripping after adjusting some files. Adding [`snazzy`](https://www.npmjs.com/package/snazzy) helped me see what the errors are:

screen shot 2016-09-22 at 4 49 56 pm

Feel free to just close if adding `snazzy` is not desired.

### CODE REVIEW

**Comment by zeke** [comment]
`snazzy` is a replacement for `standard`, isn't it? Couldn't we just use one or the other?

**Comment by crookedneighbor** [comment]
It's not a replacement. All it does is format the output of standard into a human readable format. http://npmjs.com/snazzy

**Comment by MarshallOfSound** [comment]
This looks more like the normal eslint output so 👍 from here.  Definitely more readable, and who doesn't like pretty colors? 😆

**Comment by jlord** [comment]
👍 I've used `snazzy` before

**Comment by zeke** [comment]
Looks like it works both ways: https://github.com/feross/snazzy#usage

**Comment by crookedneighbor** [comment]
Today I learned.

**Pull request merged**
